name: test workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      PRODUCTS_JIRA_TICKETS:
        description: 'Enter JIRA tickets for products'
        required: true
        default: 'default_value_if_needed'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Sumit-nainani/katsys-jlib
          ref: ${{ github.head_ref }}
          token: ${{ github.SECRET_TOKEN }}
          path: ./katsys-jlib
          submodules: recursive
      - name: Print current directory
        run: pwd
