name: test workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      PRODUCTS_JIRA_TICKETS:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Sumit-nainani/katsys-jlib
          token: ${{ secrets.SECRET_TOKEN }}
          path: ./katsys-jlib
          submodules: recursive
      - name: Print current directory
        run: pwd
